language: php
php:
	- 5.4
	- 5.5
	- 5.6
	- hhvm
	- hhvm-nightly
  
matrix:
    allow_failures:
        - php: hhvm
        - php: hhvm-nightly
    exclude:
        - php: hhvm
        - php: hhvm-nightly
    include:
        - php: hhvm
          script: Tester/tester -p php tests
        - php: hhvm-nightly
          script: Tester/tester -p php tests

before_script:
	- mkdir -p temp/cache
	- composer self-update
	- composer install --no-interaction --prefer-source --dev

script: ./vendor/bin/tester ./tests

after_failure:
	# Print *.actual content
	- for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
